[package]
name = "test/node-shim"
version = "0.1.0"
description = "Node.js shim using file-based IPC polling"

[dependencies]
"sharrattj/coreutils" = "1.0.16"
"sharrattj/bash" = "*"

[[module]]
name = "node-shim"
source = "target/wasm32-wasip1/release/wasmer-node-shim.wasm"
abi = "wasi"

[[command]]
name = "node"
module = "node-shim"
runner = "wasi"
